### ISSUE TITLE
Reinstate original copyright licence

### ISSUE THREAD

**Issue by MatthewSteeples** [phasTrak/ActuallyUseful.AutoRegister#1]
I'm not sure if you're aware, but one of the conditions of the MIT licence is that you include the original copyright for the code. If you'd like some tips on how to do that then there's a [Stackoverflow Software Engineering](https://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-do-i-handle-the-at) question that can point you in the right direction

**Comment by FXZFun** [comment]
Thanks for bringing this to my attention, and thanks for the link to more information on the topic. I believe I have modified the project to comply with the MIT licensing requirements in https://github.com/phasTrak/ActuallyUseful.AutoRegister/commit/21fbf4416fc08830b9b94014156ab1501aca889f.
